name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 1 * * SUN'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
#          - head
          - '3.1'
          - '3.0'
          - '2.7'
          - '2.6'
          - '2.5'
          - '2.4'
          - '2.3'
#          - jruby
#          - truffleruby-head
        rubygems:
          - latest
        include:
          - ruby: '2.2'
            rubygems: default
          - ruby: '2.1'
            rubygems: default
    continue-on-error: ${{ matrix.ruby == 'head' }}
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: ${{ matrix.rubygems }}
      - run: |
          bundle exec rake
